#!/bin/sh

mkdir -p /tmp
mount -t tmpfs none /tmp
cd /tmp
mkdir -p /proc
mount -t proc proc /proc
mkdir -p /sys
mount -t sysfs sysfs /sys
mkdir -p /dev/pts
mount -t devpts none /dev/pts

mkdir -p /etc/network/if-pre-up.d

export PATH=/bin:/sbin:/usr/bin:/usr/sbin
exec sh
